name: "my-containers"
services:
  redis:
    restart: unless-stopped
    ports:
      - 6379:6379
    container_name: redis
    image: redis
  
  mongo:
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: mongo
    image: mongo

  mysql:
    restart: unless-stopped
    ports:
      - 3306:3306
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  postgres:
    restart: unless-stopped
    ports:
      - 5432:5432
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root